### ISSUE TITLE
JSON responses

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/prejournal#115]
A command like
```
curl -d'["21 July 2022", "victor", "API Testing", 2, "Test integration with Prejournal"]' https://evoludata:***********@time.pondersource.com/v1/worked-hours
```
gives a plain-text response body:
```
Created movement 1
Created statement 1
```
It would be better if that was JSON, for instance
```json
{
  "movementId": 1,
  "statementId": 1
}
```

**Comment by kroky** [comment]
Is the movement ID or statement ID the one of the actual timesheet entry?

**Comment by michielbdejong** [comment]
Depends on your definition of "actual timesheet entry" :)

The movement ID uniquely identifies the economic event: The historical fact (or non-fact if the data is inaccurate) that in the physical universe worker X worked on project Y at Z time.

The statement ID uniquely identifies the speech act. For instance, row 25 in some .xls file that worker X sent to line manager Y at Z time, or the 6th entry in some array in some JSON response from an API call that was made by client X to server Y at Z time.

There can (and will) be multiple statements about each movement once neighbouring systems start syncing with a Prejournal system.

It's not strictly defined whether repeated API calls, repeated emails, repeated verbal conversations, etc. count as 1 or multiple statements. That's up to how you model it. For instance, when importing timesheet entries by pulling data out of an API, the simple approach would be to make each http response count as 1 statement, but a more efficient approach is to consider repeated responses as only 1 statement, as long as they don't disagree. Once the API response is different from the last one, that does have to be a new statement though, and then the movement details also need to change, or there need to appear conflicting movements (or movement versions) in the system. That's where it gets complex. :)

But the short answer is, if you want to deduplicate data you get out of Prejournal, you should deduplicate on movement ID and just ignore the statement ID.

**Comment by kroky** [comment]
Ok, movement ID - that is what I mean. Thanks!

**Comment by kroky** [comment]
I think that's the only missing piece with prevents me to complete Tiki to Prejournal integration. @ishifoev when do you think you can return json response here?

**Comment by ishifoev** [comment]
What json you would like to see @kroky ?

**Comment by ishifoev** [comment]
````
curl -d'["nlnet-timesh:Federated Timesheets","0","100"]' https://example:password123@time.pondersource.com/v1/print-timesheet-json
[
    {
        "id": 1,
        "worker": "ismoil",
        "project": "nlnet-timesh:Federated Timesheets",
        "timestamp_": "2022-09-12 00:00:00",
        "amount": "40",
        "description": ""
    }
]
````

**Comment by kroky** [comment]
It is the worked-hours command that returns plain text where it will be helpful to return json. Referring to this comment: https://github.com/pondersource/prejournal/issues/115#issue-1318232746

**Comment by ishifoev** [comment]
```
php src/cli-single.php  worked-hours "20 September 2021" "stichting" "Peppol for the Masses"
```

```
[
    {
        "worker": "admin",
        "project": "stichting:Peppol for the Masses",
        "timestamp_": "2021-09-20 00:00:00",
        "amount": "4",
        "description": ""
    }
]
```

**Comment by kroky** [comment]
@ishifoev I see the worked-hours command now returns JSON of the entry which is good but I still don't see a unique ID of the entry (i.e. movementId) which I can use to update the entry once imported. Can you include the movementId in this json format?

**Comment by kroky** [comment]
Also, one more issue - I create an entry with this data: `["2022-05-03", "Victor Emanouilov", "Integrate time tracker", "1", "meeting with client"]`. The returned JSON:
```
[
  {
    "worker": "evoludata",
    "project": "Victor Emanouilov:Integrate time tracker",
    "timestamp_": "2022-05-03 00:00:00",
    "amount": "1",
    "description": "meeting with client"
  }
]
```

I use the evoludata user I have for API credentials. I have no way of listing this data back with the print-timesheet-json endpoint. I tried:
`curl -d '["Victor Emanouilov:Integrate time tracker", "0", "100"]'`
and
`curl -d '["evoludata:Integrate time tracker", "0", "100"]'`
and
`curl -d '["Integrate time tracker", "0", "100"]'`
but the entry is not returned. How can I access the created entry? I guess I am not using the right parameters here.

**Comment by michielbdejong** [comment]
>  include the movementId in this json format?

 -> #127

> I have no way of listing this data back

-> #128

Other than those two follow-up issues, 

> I see the worked-hours command now returns JSON of the entry which is good

So closing this issue itself. Thanks!
