### ISSUE TITLE
Include movementId in JSON response

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/prejournal#127]

**Comment by michielbdejong** [comment]
And as discussed in today's [coordination call](https://gitter.im/federatedbookkeeping/timesheets?at=62fa28c905ad4a37014745cf) we'll support a URI for each worker and each movement, which will be included in all JSON responses everywhere, so that data can also be forwarded safely.

**Comment by michielbdejong** [comment]
And as discussed in today's [coordination call](https://gitter.im/federatedbookkeeping/timesheets?at=62fa28c905ad4a37014745cf) we'll support a URI for each worker and each movement, which will be included in all JSON responses everywhere, so that data can also be forwarded safely.

**Comment by michielbdejong** [comment]
I'll try to find some time to work on this before our next coordination call.

**Comment by gsvarovsky** [comment]
I see that the JSON response to `worked-hours` currently echoes the movement.

I confirm we need the movement ID so I can later issue an `update-entry` for the same movement ('Entry' in timeld).

**Comment by michielbdejong** [comment]
worked-hours now returns movementId and statementId, see #131.
