### ISSUE TITLE
How to write and read back

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/prejournal#128]
As described in https://github.com/pondersource/prejournal/issues/115#issuecomment-1212983347

**Comment by michielbdejong** [comment]
Ah, this is because we now have over 623 entries, and the 2nd and 3rd argument are actually `minId` and `maxId` (sorry I know it would be better practice to use offset & numPerPage here but we went for quick and easy). So I tried this locally and confirmed that:

`curl -d'["Victor Emanouilov:Integrate time tracker","0","100"]'`
returns nothing, but:
`curl -d'["Victor Emanouilov:Integrate time tracker","0","1000000"]'`
returns the entry as expected.

**Comment by kroky** [comment]
That worked, thanks!
