### ISSUE TITLE
Timeld Intergration for export and import

### ISSUE THREAD

**Issue by ishifoev** [pondersource/prejournal#138]
Working with timeld integration working with export and import.

**Comment by michielbdejong** [comment]
Whenever a new movement is added into the DB of time-pondersource-com, it should make an API call to timeld-org so that same timesheet entry will immediately appear in the database there as well.

**Comment by ishifoev** [comment]
@michielbdejong  For pushing need to save in database in same time ? I think direction, that I see you are pushing to other system the data save in other system, when you would like take data from this information you will save inside your system it will be export.

**Comment by michielbdejong** [comment]
Hm, I'm not sure if I understand your question.
Maybe it's easier to explain in the context of our live production network:
If you upload your SaveMyTime CSV to time-pondersource-com, or you run the commands from your ismoil.pj file against time-pondersource-com, then that will have 3 effects:
* entries get added in time-pondersource-com
* entries get added in timeld-org
* entries get added in timesheet-dev-evoludata-com

**Comment by michielbdejong** [comment]
Right now, only the first one is happening in practice.
This issue is about making the second one happen.
Right?

**Comment by ishifoev** [comment]
Yes, the second one is in the way, I will create a PR for it later.
