### ISSUE TITLE
option to print timesheet data for all projects

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/prejournal#157]
Maybe it's easier if we make the project name also optional, and if it's left out, just return all entries the user is allowed to see (which in open mode means just all entries of type 'worked' in the movements table)
See https://gitter.im/federatedbookkeeping/timesheets?at=63121bc19d3c186299e118f3

**Comment by michielbdejong** [comment]
For instance by making the first argument of `print-timesheet-json` optional.

**Comment by ishifoev** [comment]
@michielbdejong Yes I am working on this side, yes we can do it optional.
