### ISSUE TITLE
Unable to print just-entered worked-hours Movements

### ISSUE THREAD

**Issue by gsvarovsky** [pondersource/prejournal#163]
I have just created & updated movements 427 through 432 on time.pondersource.com with client `Federated Timesheets Virtual Organisation` and project `test/work3` but I'm unable to find them using

```
POST https://time.pondersource.com/v1/print-timesheet-json
["Federated Timesheets Virtual Organisation:test\/work3","0","10000"]
```

– I get an empty array.

I suspect my worker, which is `http://george-imac:8080/test`, may be causing the issue; but maybe if so, my `worked-hours` command should have been Forbidden, right?

Related to #133

**Comment by ishifoev** [comment]
@gsvarovsky https://github.com/pondersource/prejournal/blob/main/docs/api.md

**Comment by ishifoev** [comment]
@gsvarovsky I change the place the first start min after max, after the project will be optional you can see doc
