### ISSUE TITLE
SQLLite3 have a problem with error with Version

### ISSUE THREAD

**Issue by ishifoev** [pondersource/prejournal#17]
```SQLSTATE[HY000]: General error: 1 near "RETURNING": syntax error```

**Comment by michielbdejong** [comment]
Maybe we should stop trying to support both postgresql (in production) and sqlite (in testing). Should we just use postgresql for the unit tests as well? We can still keep using Doctrine DBAL but just focus on Postgresql only.

**Comment by ishifoev** [comment]
Yes I just move to working with PostqresSQL. Run the test and it is working I just a create PR.

**Comment by ishifoev** [comment]
I think we need to work with multiple providers but Doctrine DBAL need confugure like that they can work without problem. May be later we do it
