### ISSUE TITLE
ERROR: value too long for type character(1)

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/prejournal#99]
@ishifoev in https://github.com/pondersource/prejournal/commit/346db3dae8c5aba3c043fdfe78774b6c03799c2c#diff-32a641cba2e036c0eead09c7f05080948a7e030241f4ddd05a2b6ba9f478e067R36-R37
you changed the data type of the `sourcedocumentformat` and `sourcedocumentfilename` columns of the `statements` table from `varchar` to `character`.
Now when I try `update statements set sourcedocumentformat='asnbank-csv'` I get an error:
```
ERROR: value too long for type character(1)
```

In https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-char-varchar-text/ it says that "Unlike VARCHAR, The CHARACTER or  CHAR without the length specifier (n) is the same as the CHARACTER(1) or CHAR(1)."

Was this intentional, that you cannot store longer strings in these two fields? Maybe we should change them back to `varchar`?

**Comment by ishifoev** [comment]
@michielbdejong It is the problem of posgres sometime they say it is ok working with varchar sometimes with char. I change it to varchar again.
